# Copyright 2018, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: cpp

sudo: false

os:
  - linux
  - osx

osx_image: xcode9.2

git:
  submodules: false

addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - zip

before_install:
  - export CC=
  - export CXX=

install:
#  - cd ..
#  - git clone https://github.com/wilton-iot/wilton
#  - cd wilton
  - bash ./resources/ci/travis-checkout.sh

before_script:
  - echo "PR support is enabled for root repo"

script:
  - bash ./resources/ci/travis.sh
  - if [ "x" != "x${TRAVIS_TAG}" ] ; then
      if [ "xlinux" = "x${TRAVIS_OS_NAME}" ] ; then
          export ARTIFACT_PATH=`pwd`/build/wilton_${TRAVIS_TAG}.apk ;
          sha256sum ${ARTIFACT_PATH} > ${ARTIFACT_PATH}.sha256 ;
      else
          export ARTIFACT_PATH=`pwd`/build/wilton_${TRAVIS_TAG}_macos.zip ;
          shasum -a 256 ${ARTIFACT_PATH} > ${ARTIFACT_PATH}.sha256 ;
      fi ;
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MMYQqqpaQtskcbWndVZ0gzHHMvPSfCNTYFxfYUk4VMnT0pBFzVgPULkiYAbpxcaj/ODW0nXeeYgq9/QjrJhiDLApsaAwz1TSWBjuYjD2XgjV/6xEgB7DyCmDX+Y2mMZyOvDTVqJDBLY/f2KDRGCDoNO38zrX0Vp5a6RFqrrVgIaMiqqVV+32VUfcTpE7icfBk9Z0+BB9WdNYKqi9y66X9rK6AGXCZeE59eNjtzx/5fne8jfv3tZ7m3B7kUNpZqxOQKCNeL3GwTQyKK2iBRuqm1N6opyaTH2ddcPDH2Pz9OV2jjdC1fe9u7A2m9QLEJHd83nJrEoqZtbwMNLG3xMondAMSYhsPoWg4whbF7FIF6LE5K7UQFEPN61TlU85i299QiKMqVX8DuQEUv1JpHrGHNHGn1bEZThVI2STSYLjWjQycie0eWUtb0Z9Cw8+lR/hJaj+aJj5jA9dI8ND87Xu+1MYIZQNhl5CSPuQ02YTcu+xZYD4ah/4dq7U9xcWahvpf2ft4NCNgEvCoFqDci6Mc2OhaK3FqhFj/5W+H/dRl/3cgKuTSpXQ5/MfZQEAJwfvipE3rVTFVzUMLVWASVfbGbT+hPJkDpNTq0B9Ww4kHnhlz4DZQkIhgKoQhG0KGSMoYAO8hwKQ30l1rEgd/KpSEgpyd5ZuQEHdt1O2Wn02m6w=
  file:
    - ${ARTIFACT_PATH}
#    - ${ARTIFACT_PATH}.sha256 
  on:
    repo: wilton-iot/wilton
    tags: true
