# Copyright 2018, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: cpp

os:
  - linux
  - osx

osx_image: xcode9.2

git:
  submodules: false

addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - zip
      - qemu-user-static

before_install:
  - export CC=
  - export CXX=

install:
#  - cd ..
#  - git clone https://github.com/wiltonruntime/wilton
#  - cd wilton
  - bash ./resources/ci/travis-checkout.sh

before_script:
  - echo "PR support is enabled for root repo"

script:
  - bash ./resources/ci/travis.sh
  - if [ "x" != "x${TRAVIS_TAG}" ] ; then
      if [ "xlinux" = "x${TRAVIS_OS_NAME}" ] ; then
          export ARTIFACT_1_PATH=`pwd`/wilton_${TRAVIS_TAG}.apk ;
          export ARTIFACT_2_PATH=`pwd`/build/wilton_${TRAVIS_TAG}_rpi.zip ;
      else
          export ARTIFACT_1_PATH=`pwd`/build/wilton_${TRAVIS_TAG}_macos.zip ;
          export ARTIFACT_2_PATH=`pwd`/build/wilton_${TRAVIS_TAG}_macos.zip ;
      fi ;
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: E8R0tnZi1IwL9aQ4S/4GCk9XryU+3fDDHuvcMcz9vjtZWGitQxEL9Ys/g2NAjUG7+r5CYtPUa01gjf1LHV9W4yHMptVm8N5wL/RmIw+dPX2+wdbGlziuO9GzOyWt1E3lPfx3h9bIJqdkuf8uM65OZSQYsRTf4U/LdS/1W5of1RUKBNNyNOWN4OZtNxC67NyJ5gOkWQVIs6HVZeVpDRP3svbT8SfpnfR/5dlh8cIJcR/c4iqCLRHd4CmxDoMsEBm9dXFxlCl/XY+dbNubkyE1MWDaGu9M0AlQqAlYpd+oSDqKtfF9RSaKZYjdB8eivI5KofDGQ+mSwrNhu74/qp94sMDGa6mNQ7UiTQQ8jfmgxlC+XRD+W2xHmkdbhSgcNbu0PuWlkKwfexsatXiV19nsjA7Nmf+NDCCqydIJPKTKLkSa6NHB49y2k9sLRHgxwy5O66/FiD2CN8qw/jk0o+a4jchv6NF37seUPREolGBe9nCcmFGCfhEzmTe+vcXYa+ko6YnAElKc7oJBNDZHg3x6V5WC9x11SmEXyZVIx6tMe5ZfKXaa6J61YktT2cBA4kYS8xPyM6AO/ZOO34eKwT2vbOEW69PNgJO9PTff7BgL7jSjltxhxBkMxrhWh81/nG/Bd7CeuURDq+Uc6psXUuxhEhPkCcQ1V5vJVBCjhRDepcY=
  file:
    - ${ARTIFACT_1_PATH}
    - ${ARTIFACT_2_PATH}
  on:
    repo: wiltonruntime/wilton
    tags: true
